# 认证服务配置
server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    connection-timeout: 20000

spring:
  application:
    name: rpc-auth-service
  
  profiles:
    active: dev
  
  # 数据源配置
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rpc_auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      hikari:
        pool-name: MasterHikariPool
        minimum-idle: 5
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
    
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/rpc_auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      hikari:
        pool-name: SlaveHikariPool
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000ms
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  
  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "auth:cache:"

# 日志配置
logging:
  level:
    root: INFO
    com.hejiexmu.rpc.auth: DEBUG
    org.springframework.security: DEBUG
    org.springframework.jdbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/auth-service.log
    max-size: 100MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# 自定义配置
auth:
  # JWT配置
  jwt:
    secret: "mySecretKey123456789012345678901234567890"
    access-token-expiration: 3600  # 1小时
    refresh-token-expiration: 604800  # 7天
    issuer: "rpc-auth-service"
    
  # 会话配置
  session:
    max-sessions-per-user: 5
    session-timeout: 3600  # 1小时
    cleanup-interval: 300  # 5分钟
    
  # 密码策略配置
  password:
    min-length: 8
    max-length: 100
    require-uppercase: true
    require-lowercase: true
    require-digit: true
    require-special-char: true
    max-login-attempts: 5
    lockout-duration: 300  # 5分钟
    
  # 安全配置
  security:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
    
    rate-limit:
      enabled: true
      requests-per-minute: 60
      burst-capacity: 100

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/rpc_auth_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    slave:
      url: jdbc:mysql://localhost:3307/rpc_auth_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  
  redis:
    database: 1

logging:
  level:
    com.hejiexmu.rpc.auth: DEBUG
    org.springframework.security: DEBUG

---
# 测试环境配置
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    master:
      url: jdbc:mysql://test-mysql:3306/rpc_auth_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    slave:
      url: jdbc:mysql://test-mysql-slave:3307/rpc_auth_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  
  redis:
    host: test-redis
    database: 2

logging:
  level:
    root: WARN
    com.hejiexmu.rpc.auth: INFO

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    master:
      url: jdbc:mysql://prod-mysql:3306/rpc_auth?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
      username: ${DB_USERNAME:rpc_user}
      password: ${DB_PASSWORD:}
      hikari:
        maximum-pool-size: 50
    slave:
      url: jdbc:mysql://prod-mysql-slave:3307/rpc_auth?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
      username: ${DB_USERNAME:rpc_user}
      password: ${DB_PASSWORD:}
      hikari:
        maximum-pool-size: 30
  
  redis:
    host: prod-redis
    password: ${REDIS_PASSWORD:}
    database: 0
    cluster:
      nodes:
        - prod-redis-1:6379
        - prod-redis-2:6379
        - prod-redis-3:6379

auth:
  jwt:
    secret: ${JWT_SECRET:}
    
logging:
  level:
    root: WARN
    com.hejiexmu.rpc.auth: INFO
  file:
    name: /var/log/auth-service/auth-service.log