# RPC Consumer Sample Configuration
server:
  port: 8071
  servlet:
    context-path: /

spring:
  application:
    name: rpc-consumer-sample
  profiles:
    active: dev

# RPC Framework Configuration
rpc:
  enabled: true
  
  # Service Registry Configuration
  registry:
    type: zookeeper
    address: 192.168.109.103:2181
    session-timeout: 30000
    connection-timeout: 15000
    retry-times: 3
  
  # Consumer Configuration
  consumer:
    enabled: true
    timeout: 5000
    retry-count: 3
    connection-pool-size: 10
  
  # Provider Configuration (not used in consumer)
  # 注意：消费者不再需要配置序列化器，框架会自动从服务发现获取

# Logging Configuration is now handled by logback-spring.xml

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Application Info
info:
  app:
    name: RPC Consumer Sample
    description: Spring Boot RPC Framework Consumer Example
    version: 1.0.0
    author: hejiexmu
  java:
    version: ${java.version}
  spring:
    version: ${spring-boot.version}