# RPC Provider Sample Configuration - Instance 3
server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: rpc-provider-sample

# RPC Framework Configuration
rpc:
  enabled: true
  
  # Service Registry Configuration
  registry:
    type: zookeeper
    address: 192.168.109.103:2181
    session-timeout: 30000
    connection-timeout: 15000
    retry-times: 3
  
  # Provider Configuration
  provider:
    host: localhost
    port: 9083
    serializer: 1
    worker-threads: 10
  
  # Consumer Configuration (for health checks)
  consumer:
    timeout: 5000
    retry-count: 3
    connection-pool-size: 10

# Logging Configuration
logging:
  level:
    root: INFO
    com.hejiexmu.rpc: DEBUG
    com.rpc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/rpc-provider-8083.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Application Info
info:
  app:
    name: RPC Provider Sample - Instance 3
    description: Spring Boot RPC Framework Provider Example - Port 8083
    version: 1.0.0
    author: hejiexmu
    instance: 3
  java:
    version: ${java.version}
  spring:
    version: ${spring-boot.version}